version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/similar-songs
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/similar-songs/node_modules
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: ${RAILS_ENV}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
volumes:
  mysql_data:
  bundle_data:
  node_modules: