default: &default
  adapter: mysql2
  encoding: utf8
  username: test_user
  password: password
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: github_actions_ci

test:
  <<: *default
  database: github_actions_ci