name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: ruby/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Rubocop Check
        run: bundle exec rubocop

      - name: Run RSpec tests
        run: bundle exec rspec

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build assets with esbuild
        run: npm run build
        working-directory: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Deploy to production server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_APP_DIR: ${{ secrets.SERVER_APP_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $SERVER_USER@$SERVER_HOST << EOF
            cd $SERVER_APP_DIR

            # 最新のコードのpullとDockerコンテナの停止
            git pull orign master
            docker compose -f docker-compose.production.yml down

            # Gemのインストール
            docker-compose -f docker-compose.production.yml run --rm web bundle install

            # DBのマイグレーション
            docker-compose -f docker-compose.production.yml run --rm web bundle exec rails db:migrate

            # アセットのプリコンパイル
            docker-compose -f docker-compose.production.yml run --rm web bundle exec rails assets:precompile

            # Dockerコンテナの立ち上げ
            docker-compose -f docker-compose.production.yml up -d --build
          EOF
          rm private_key.pem
